[SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "projetoplanilhacv"
private_key_id = "2741392664d8f375589ff3b02c967cf86286f6e6"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIE... chave completa até \n-----END PRIVATE KEY-----\n"
client_email = "acesso-planilha@projetoplanilhacv.iam.gserviceaccount.com"
client_id = "111917108364836829715"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/acesso-planilha%40projetoplanilhacv.iam.gserviceaccount.com"
